kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - argocd.yml
  - scpi-invest-plus-int.yml
  - scpi-invest-plus-qua.yml
  - scpi-invest-plus-prd.yml
  - keycloak.yml
  - cert-manager.yml
  - external-dns.yml
  - jenkins.yml
  - sonarqube.yml
  - kafka.yml
  - logging.yml
  - monitoring.yml
  - vault.yml
