apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - namespace.yml
  - ingress.yml
  - certificate.yml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    releaseName: vault
    version: 0.30.0
    valuesFile: values.yml