extraVolumes:
  - name: providers-volume
    emptyDir: {}

extraVolumeMounts:
  - name: providers-volume
    mountPath: /opt/bitnami/keycloak/providers

extraInitContainers:
  - name: download-plugins
    image: curlimages/curl:8.13.0
    command:
      - sh
      - -c
      - |
        mkdir -p /plugins
        curl -L -o /plugins/keycloak-webhook-provider-core.jar https://github.com/vymalo/keycloak-webhook/releases/download/v0.8.4/keycloak-webhook-provider-core-0.8.4-all.jar
        curl -L -o /plugins/keycloak-webhook-provider-http.jar https://github.com/vymalo/keycloak-webhook/releases/download/v0.8.4/keycloak-webhook-provider-http-0.8.4-all.jar
        cp /plugins/*.jar /providers/
    volumeMounts:
      - name: providers-volume
        mountPath: /providers
