apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  template:
    spec:
      volumes:
        - name: providers-volume
          emptyDir: {}

      initContainers:
        - name: download-plugins
          image: curlimages/curl:8.13.0
          command:
            - sh
            - -c
            - |
              mkdir -p /plugins
              curl -L -o /plugins/keycloak-webhook-provider-core.jar https://github.com/vymalo/keycloak-webhook/releases/download/v0.8.4/keycloak-webhook-provider-core-0.8.4-all.jar
              curl -L -o /plugins/keycloak-webhook-provider-http.jar https://github.com/vymalo/keycloak-webhook/releases/download/v0.8.4/keycloak-webhook-provider-http-0.8.4-all.jar
              cp /plugins/*.jar /providers/
          volumeMounts:
            - name: providers-volume
              mountPath: /providers

      containers:
        - name: keycloak
          volumeMounts:
            - name: providers-volume
              mountPath: /opt/bitnami/keycloak/providers
