postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: keycloak_postgres
    database: bitnami_keycloak

auth:
  adminUser: admin
  adminPassword: admin

extraEnvVars:
  - name: KC_HOSTNAME_ADMIN
    value: "https://keycloak.check-consulting.net"
  - name: KC_HOSTNAME
    value: "https://keycloak.check-consulting.net"
  - name: KC_PROXY
    value: edge
  - name: WEBHOOK_HTTP_BASE_PATH
    value: "https://int.scpi-invest-plus-api.check-consulting.net/api/v1/webhook/keycloak"
  - name: WEBHOOK_HTTP_AUTH_USERNAME
    value: "admin"
  - name: WEBHOOK_HTTP_AUTH_PASSWORD
    value: "admin"