postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: keycloak_postgres
    database: bitnami_keycloak

auth:
  adminUser: admin
  adminPassword: admin

extraEnvVars:
  - name: KC_HOSTNAME_ADMIN
    value: "https://keycloak.check-consulting.net"
  - name: KC_HOSTNAME
    value: "https://keycloak.check-consulting.net"
  - name: KC_PROXY
    value: edge
  - name: WEBHOOK_HTTP_BASE_PATH
    value: "https://int.scpi-invest-plus-api.check-consulting.net/api/v1/webhook/keycloak"
  - name: WEBHOOK_HTTP_AUTH_USERNAME
    value: "admin"
  - name: WEBHOOK_HTTP_AUTH_PASSWORD
    value: "admin"


extraVolumes:
  - name: providers-volume
    emptyDir: {}

extraVolumeMounts:
  - name: providers-volume
    mountPath: /opt/bitnami/keycloak/providers

extraInitContainers:
  - name: download-plugins
    image: curlimages/curl:8.1.2
    command:
      - sh
      - -c
      - |
        mkdir -p /plugins
        # Download the plugins from GitHub releases
        curl -L -o /plugins/keycloak-webhook-provider-core.jar https://github.com/vymalo/keycloak-webhook/releases/download/v0.8.4/keycloak-webhook-provider-core-0.8.4-all.jar
        curl -L -o /plugins/keycloak-webhook-provider-amqp.jar https://github.com/vymalo/keycloak-webhook/releases/download/v0.8.4/keycloak-webhook-provider-amqp-0.8.4-all.jar
        curl -L -o /plugins/keycloak-webhook-provider-http.jar https://github.com/vymalo/keycloak-webhook/releases/download/v0.8.4/keycloak-webhook-provider-http-0.8.4-all.jar
        cp /plugins/*.jar /providers/
    volumeMounts:
      - name: providers-volume
        mountPath: /providers
