apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-batch-tls
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt
  secretName: kibana-batch-tls
  dnsNames:
    - kibana-batch.check-consulting.net
  usages:
    - digital signature
    - key encipherment
