apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scpi-invest-plus-api-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: scpi-invest-plus-api-secret
    creationPolicy: Owner
  data:
    - secretKey: spring.datasource.url
      remoteRef:
        key: scpi-invest-plus-api/config
        property: spring.datasource.url
    - secretKey: spring.datasource.username
      remoteRef:
        key: scpi-invest-plus-api/config
        property: spring.datasource.username
    - secretKey: spring.datasource.password
      remoteRef:
        key: scpi-invest-plus-api/config
        property: spring.datasource.password
    - secretKey: spring.webhook.username
      remoteRef:
        key: scpi-invest-plus-api/config
        property: spring.webhook.username
    - secretKey: spring.webhook.password
      remoteRef:
        key: scpi-invest-plus-api/config
        property: spring.webhook.password
    - secretKey: keycloak.adminUsername
      remoteRef:
        key: scpi-invest-plus-api/config
        property: keycloak.adminUsername
    - secretKey: keycloak.adminPassword
      remoteRef:
        key: scpi-invest-plus-api/config
        property: keycloak.adminPassword