image:
  tag: 8c231885adeab63de2a36aedb7170d537ab256d3

ingressPrefix: int
ingressKibanaPrefix: int
ingressPgWebPrefix: integration

application:
  environment: int
elasticsearch:
  hostname: elasticsearch-batch.scpi-invest-plus-int
