image:
  tag: 83d0a6886e4597162ff6213a839873a437169885

ingressPrefix: int
ingressKibanaPrefix: int
ingressPgWebPrefix: integration

application:
  environment: int
elasticsearch:
  hostname: elasticsearch-batch.scpi-invest-plus-int
