image:
  tag: 5e11649eee45036f56b54c0e4521c1fc4c421d2a

ingressPrefix: int
ingressKibanaPrefix: int
ingressPgWebPrefix: integration

application:
  environment: int
elasticsearch:
  hostname: elasticsearch-batch.scpi-invest-plus-int
