apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      version: 0.9.9
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
    interval: 5m
    values:
      installCRDs: true
