apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          command: ["/bin/bash", "-c"]
          args:
            - |
              export KAFKA_BROKER_ID=$(echo $HOSTNAME | grep -o '[0-9]*')
              echo "Using broker.id=$KAFKA_BROKER_ID"
              sed -i "s/^broker.id=.*$/broker.id=$KAFKA_BROKER_ID/" /opt/bitnami/kafka/config/server.properties
              /opt/bitnami/scripts/kafka/run.sh
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-$(hostname).kafka.svc.cluster.local:9092"


---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
