apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka

helmCharts:
  - name: kafka
    repo: https://charts.bitnami.com/bitnami
    releaseName: kafka
    version: 31.3.1
    valuesFile: values.yml