apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chmod -R 472:472 /mnt/grafana-data /var/lib/grafana"]
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: test
            - name: GF_SMTP_ENABLED
              value: "true"
            - name: GF_SMTP_HOST
              value: "smtp.gmail.com:587"
            - name: GF_SMTP_USER
              value: "jubatouam61@gmail.com"
            - name: GF_SMTP_PASSWORD
              value: "tjnpbtytxzjxxpzr"
            - name: GF_SMTP_FROM_ADDRESS
              value: "jubatouam61@gmail.com"
            - name: GF_SMTP_FROM_NAME
              value: "Grafana Alerts"
            - name: GF_SMTP_SKIP_VERIFY
              value: "false"
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000